# Default values for stash-postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  registry: stashed
  repository: stash-postgres
  tag: "9.6"

# optional argument to send pgdump or psql command
backup:
  args: ""
restore:
  args: ""
